CREATE TABLE IF NOT EXISTS playlists (
  playlist_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  last_edited DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  likes INT DEFAULT 0,
  dislikes INT DEFAULT 0,
  songs JSON NOT NULL,

  user_id BIGINT NOT NULL,

  FOREIGN KEY (user_id) REFERENCES users(user_id)
);
